### PR TITLE
Update for Minecraft 1.18.2 (ReloadableResourceManagerImpl).

### PR DESCRIPTION
**Pull request by gniftygnome**
Pretty small update for 1.18.2 but then it won't work for <1.18.2.

### CODE REVIEW

**Comment by osfanbuff63** [comment]
*instantly clones and builds* (lol)

**Comment by osfanbuff63** [comment]
Thanks so much! If you are able to, I need some help updating [Command Block IDE](https://www.curseforge.com/minecraft/mc-mods/command-block-ide) to 1.18.2 (it's the last mod I'm waiting on to update to 1.18.2) I've started in arm32x/command-block-ide#11, but I don't know Java, so I can't patch the errors with mixins.

**Comment by Julienraptor01** [comment]
I now tested this fork for some time and the features i tried to use all worked.

**Review by osfanbuff63 — APPROVED** [review]
Same here. 1.19 has already been released, and I have had no (!) problems with this fork on 1.18.2. Are any maintainers still here? It seems like the project is inactive.

**Comment by gniftygnome** [comment]
I'm not quite as sure about it, but see PR #27 for a 1.19 version.

**Comment by Julienraptor01** [comment]
> I'm not quite as sure about it, but see PR #27 for a 1.19 version.

I just hope they won't skip 1.18.2 as this is the latest version of 1.18.x and many will still use it while waiting for mods to update to 1.19

**Comment by osfanbuff63** [comment]
> I'm not quite as sure about it, but see PR #27 for a 1.19 version.

So fast, thanks a **lot**!

> I just hope they won't skip 1.18.2 as this is the latest version of 1.18.x and many will still use it while waiting for mods to update to 1.19

Me being one of them, and I know others as well that will be doing that.

**Comment by osfanbuff63** [comment]
> > I'm not quite as sure about it, but see PR #27 for a 1.19 version.
> 
> I just hope they won't skip 1.18.2 as this is the latest version of 1.18.x and many will still use it while waiting for mods to update to 1.19

Me being one of them, and I know others as well that will be doing that.

**Pull request merged**
